tor_bridges: |
  Bridge obfs4 89.166.164.223:8080 02F00A33017A24E99112E5CA498AECD204F913F3 cert=eWfCYOE/3kdmDpYy/tT0CuKI01dWKY6BtSAMSu0uuD4ixo7RE4/av+0fNjw4sbZmORLKVQ iat-mode=0
  Bridge obfs4 82.65.223.6:46153 F132FE9E31F811DAE0E8907F5455C7B3E1A57014 cert=Dqm58CU6XLLrnalDuwds/NQ2TAOnHvLBaEdTTVP4XJiqJPyS6QNaBHVNqGrra+qG2XR2Ow iat-mode=0
  Bridge obfs4 51.38.220.224:30996 22494A012CFA8C88B1D907E2CCB8409AC35B537B cert=dOPijSCG6FD89fYv5N2F9QoeK1od3tpG6VBE/kMY0Bt1aW/7aXPIzsENDoLWZe43gI8efw iat-mode=0
  Bridge obfs4 57.128.59.134:24102 A4AE24E2BF9CCD542A9F2794D534D13A39F2F161 cert=dX8/pc880Ne2bMEfmw75yFmsbnoZ+rWl4NDIjrei/ADZ/nHAiYTUw2HodxTIW8cWaKEkKQ iat-mode=0
